{% set name = "behave-django" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/behave-django-{{ version }}.tar.gz
  sha256: aecbc535699517100c1e443eadb4a5d761c2b1d2f4364d88c8e74a236c915c9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - behave

test:
  imports:
    - behave_django
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/behave/behave-django
  summary: Behave BDD integration for Django
  doc_url: https://pythonhosted.org/behave-django/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
